Repository E3SM-Project/EKAT, pull requests merged in 2020-09, with the labels that each got.

#29 Flattening all namespaces within ekat except impl/detail
  src/ekat/ekat_pack.hpp
  src/ekat/ekat_pack_kokkos.hpp
  src/ekat/ekat_parameter_list.hpp
  src/ekat/ekat_session.cpp
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
  src/ekat/kokkos/ekat_kokkos_meta.hpp
  src/ekat/kokkos/ekat_kokkos_types.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  src/ekat/std_meta/ekat_std_any.hpp
  src/ekat/std_meta/ekat_std_enable_shared_from_this.hpp
  src/ekat/std_meta/ekat_std_utils.hpp
  src/ekat/util/ekat_arch.cpp
  src/ekat/util/ekat_arch.hpp
  src/ekat/util/ekat_array_io.cpp
  src/ekat/util/ekat_catch_main.cpp
  src/ekat/util/ekat_factory.hpp
  src/ekat/util/ekat_file_utils.hpp
  src/ekat/util/ekat_lin_interp.hpp
  src/ekat/util/ekat_lin_interp_impl.hpp
  src/ekat/util/ekat_math_utils.hpp
  src/ekat/util/ekat_md_array.hpp
  src/ekat/util/ekat_rational_constant.hpp
  src/ekat/util/ekat_scaling_factor.hpp
  src/ekat/util/ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.hpp
  src/ekat/util/ekat_test_session.cpp
  src/ekat/util/ekat_test_utils.cpp
  src/ekat/util/ekat_test_utils.hpp
  src/ekat/util/ekat_tridiag.hpp
  src/ekat/util/ekat_units.hpp
  src/ekat/util/ekat_upper_bound.hpp
  tests/algorithm/lin_interp_test.cpp
  tests/algorithm/tridiag_bfb.cpp
  tests/algorithm/tridiag_tests.cpp
  tests/algorithm/tridiag_tests.hpp
  tests/algorithm/tridiag_tests_correctness.cpp
  tests/algorithm/tridiag_tests_performance.cpp
  tests/kokkos/kokkos_utils_tests.cpp
  tests/kokkos/workspace_tests.cpp
  tests/pack/pack_kokkos_tests.cpp
  tests/pack/pack_tests.cpp
  tests/utils/CMakeLists.txt
  tests/utils/upper_bound_test.cpp
  tests/utils/util_tests.cpp
Labels: code cleanup

#33 Added install targets for testing micro-libs.
  src/ekat/CMakeLists.txt
Labels: build, testing

#34 add parallel_reduce
  src/ekat/ekat_workspace_impl.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  src/ekat/util/ekat_lin_interp_impl.hpp
  tests/kokkos/kokkos_utils_tests.cpp
  tests/kokkos/workspace_tests.cpp
  tests/pack/pack_kokkos_tests.cpp
Labels: AT: AUTOMERGE

#41 Add PackInfo struct for pack index arithmetics.
  src/ekat/CMakeLists.txt
  src/ekat/ekat_pack_utils.hpp
  tests/pack/CMakeLists.txt
  tests/pack/pack_utils_tests.cpp
Labels: AT: AUTOMERGE, Packs, enhancement

#42 Bartgol/default bfb
  CMakeLists.txt
  ekat_config.h.in
  src/ekat/ekat.hpp
  src/ekat/ekat_pack.hpp
  src/ekat/ekat_workspace_impl.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  src/ekat/util/ekat_lin_interp_impl.hpp
  tests/kokkos/kokkos_utils_tests.cpp
  tests/kokkos/workspace_tests.cpp
  tests/pack/pack_kokkos_tests.cpp
  tests/pack/pack_tests.cpp
Labels: AT: AUTOMERGE, code usability, enhancement

#43 Some cmake upgrades/fixes
  CMakeLists.txt
  cmake/Ekat.cmake
  cmake/Kokkos.cmake
  cmake/YamlCpp.cmake
Labels: AT: AUTOMERGE, cmake

#46 Some more cmake upgrades
  CMakeLists.txt
  cmake/EkatConfig.cmake.in
  cmake/mpi/EkatMpiUtils.cmake
  cmake/mpi/EkatSetNvccWrapper.cmake
  cmake/mpi/TryCompileMPICH.cpp
  cmake/mpi/TryCompileOpenMPI.cpp
  cmake/pkg_build/EkatBuildEkat.cmake
  cmake/pkg_build/EkatBuildKokkos.cmake
  cmake/pkg_build/EkatBuildYamlCpp.cmake
  src/ekat/CMakeLists.txt
  src/ekat/ekat.hpp
  src/ekat/ekat_config.h.in
  src/ekat/kokkos/ekat_kokkos_types.hpp
  tests/io/CMakeLists.txt
  tests/utils/CMakeLists.txt
  tests/utils/kernel_assert.cpp
Labels: cmake, code cleanup, code usability, enhancement

#47 make expm1 avail to packs
  cmake/machine-files/kokkos/intel-bdw.cmake
  cmake/machine-files/lassen.cmake
  cmake/machine-files/quartz.cmake
  src/ekat/ekat_pack.hpp
  tests/pack/pack_tests.cpp
Labels: AT: AUTOMERGE, Packs

#54 Fix overload of operator/ for Units
  src/ekat/util/ekat_units.hpp
  tests/units/units.cpp
Labels: AT: AUTOMERGE, bugfix

#50 Bug fix in ekat_catch_main
  src/ekat/util/ekat_catch_main.cpp
Labels: AT: AUTOMERGE, bugfix, testing

#55 Using NEW behavior for cmp0074
  CMakeLists.txt
Labels: AT: AUTOMERGE, cmake, code quality

#56 fix view_reduction
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  tests/kokkos/kokkos_utils_tests.cpp
Labels: AT: AUTOMERGE, bugfix, kokkos
