Repository E3SM-Project/EKAT, pull requests merged in 2020-12, with the labels that each got.

#77 Add support for bool data, add tests for this
  src/ekat/ekat_pack_kokkos.hpp
  tests/pack/pack_kokkos_tests.cpp
Labels: AT: AUTOMERGE

#78 add tridiag namespace
  src/ekat/util/ekat_tridiag.hpp
  tests/algorithm/tridiag_bfb.cpp
  tests/algorithm/tridiag_tests_correctness.cpp
  tests/algorithm/tridiag_tests_performance.cpp
Labels: AT: AUTOMERGE, code quality

#79 Improvement to EkatCreateUnitTest
  cmake/EkatCreateUnitTest.cmake
  tests/pack/pack_kokkos_tests.cpp
Labels: AT: AUTOMERGE, cmake, enhancement

#80 host_to_device and device_to_host now use vectors
  src/ekat/ekat_pack_kokkos.hpp
  tests/pack/pack_kokkos_tests.cpp
Labels: AT: AUTOMERGE
