Repository E3SM-Project/EKAT, pull requests merged in 2020-11, with the labels that each got.

#71 When checking for fenv.h, use the cxx compiler.
  CMakeLists.txt
Labels: AT: AUTOMERGE, bug, cmake

#73 Add 3d device-host functions
  src/ekat/ekat_pack_kokkos.hpp
  tests/pack/pack_kokkos_tests.cpp
Labels: Packs

#75 change macro
  src/ekat/ekat.hpp
  src/ekat/ekat_config.h.in
Labels: AT: AUTOMERGE

#76 Implemented a Jaccard string similarity index function (and a test).
  src/ekat/util/ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.hpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, enhancement
