Repository E3SM-Project/EKAT, pull requests merged in 2020-08, with the labels that each got.

#2 Added welcome messages
  .github/config.yml
Labels: enhancement

#3 Small change in SetCompilerFlags
  cmake/EkatSetCompilerFlags.cmake
Labels: bugfix, cmake

#11 Fix to EkatCreateUnitTest
  cmake/EkatCreateUnitTest.cmake
Labels: AT: AUTOMERGE, bugfix, cmake

#17 Fix overload of operator<< for std::vector
  src/ekat/std_meta/ekat_std_utils.hpp
Labels: AT: AUTOMERGE, bugfix

#15 Added another template parameter to host_device/device_to_host functions.
  src/ekat/ekat_pack_kokkos.hpp
Labels: enhancement

#21 Mac build
  CMakeLists.txt
  ekat_config.h.in
  src/ekat/ekat_assert.cpp
  src/ekat/ekat_assert.hpp
  src/ekat/ekat_pack.hpp
  src/ekat/util/ekat_arch.cpp
  src/ekat/util/ekat_feutils.hpp
  tests/utils/debug_tools_tests.cpp
Labels: AT: AUTOMERGE, enhancement, new feature

#22 Added utility for string similarity check.
  src/ekat/ekat_parse_yaml_file.cpp
  src/ekat/util/ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.hpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, utility

#24 Add none() method to Mask
  src/ekat/ekat_pack.hpp
  tests/pack/pack_tests.cpp
Labels: AT: AUTOMERGE, Packs, enhancement

#25 Modifying IMPL_KERNEL_THROW to accept runtime string msg
  src/ekat/ekat_assert.hpp
  tests/algorithm/CMakeLists.txt
  tests/kokkos/CMakeLists.txt
  tests/pack/CMakeLists.txt
  tests/utils/CMakeLists.txt
  tests/utils/kernel_assert.cpp
Labels: AT: AUTOMERGE, enhancement
