Repository E3SM-Project/EKAT, pull requests merged in 2021-11, with the labels that each got.

#159 Fix name of EKAT_TEST_LAUNCHER_BUFFER
  CMakeLists.txt
  cmake/EkatCreateUnitTest.cmake
Labels: AT: AUTOMERGE

#160 Add support for reusing executables to EkatCreateUnitTest macro
  cmake/EkatCreateUnitTest.cmake
Labels: AT: AUTOMERGE

#161 Prepare for v1
  README.md
  extern/catch2/LICENSE.txt
Labels: AT: AUTOMERGE, code cleanup

#164 --kokkos-ndevices -> --kokkos-num-devices
  src/ekat/ekat_session.cpp
Labels: AT: AUTOMERGE

#163 For Catch2 unit tests, suppress colored output in ctest tests
  cmake/EkatCreateUnitTest.cmake
Labels: AT: AUTOMERGE, testing, Quality Of Life

#166 Split EkatCreateUnitTest in two macros
  cmake/EkatCreateUnitTest.cmake
  tests/ekat_test_config.h.in
Labels: cmake, AT: AUTOMERGE

#162 Have catch2 print successful tests output only once
  extern/catch2/include/catch2/catch.hpp
Labels: AT: AUTOMERGE, testing, Quality Of Life

#167 test-launcher: fixes for LLNL machines syrah and quartz
  bin/test-launcher
Labels: AT: AUTOMERGE

#168 Reduce duplication of argument lists for create unit test functions
  cmake/EkatCreateUnitTest.cmake
  cmake/EkatUtils.cmake
Labels: AT: AUTOMERGE
