Repository E3SM-Project/EKAT, pull requests merged in 2021-04, with the labels that each got.

#96 Make pack ctor from scalar *not* explicit
  src/ekat/ekat_pack.hpp
Labels: AT: AUTOMERGE, Packs, code usability

#98 Add some overloads for volatile Packs
  src/ekat/ekat_pack.hpp
Labels: AT: AUTOMERGE, Packs, bugfix, kokkos

#97 Aarondonahue/any cast throw exception
  src/ekat/ekat_parameter_list.hpp
  src/ekat/std_meta/ekat_std_any.hpp
  tests/io/yaml_parser.cpp
Labels: AT: AUTOMERGE, enhancement

#101 Upgrades to Pack's masked operations
  src/ekat/ekat_pack.hpp
  src/ekat/util/ekat_math_utils.hpp
  tests/pack/pack_tests.cpp
Labels: AT: AUTOMERGE, Packs, enhancement

#103 Removed warning from ParameterList method
  src/ekat/ekat_parameter_list.hpp
  src/ekat/std_meta/ekat_std_any.hpp
Labels: AT: AUTOMERGE, code cleanup

#105 add Workspace::reserve_n_contiguous_sub_blocks
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
  tests/kokkos/workspace_tests.cpp
Labels: AT: AUTOMERGE

#106 Yet another overload of pack's op= with volatile cv
  src/ekat/ekat_pack.hpp
Labels: AT: AUTOMERGE, enhancement
