Repository E3SM-Project/EKAT, pull requests merged in 2021-03, with the labels that each got.

#88 Add support for using valgrind on all created tests
  CMakeLists.txt
  cmake/EkatCreateUnitTest.cmake
  tests/utils/upper_bound_test.cpp
  valgrind_support/CMakeLists.txt
  valgrind_support/gen_sup.sh
  valgrind_support/mpi_hw.cxx
  valgrind_support/serial_hw.cxx
Labels: AT: AUTOMERGE, cmake, enhancement

#91 Add possibility of whole-string-matching to Jaccard similarity algorithm
  src/ekat/util/ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.hpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, utility

#92 Bug fix to gather_tokens in ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.cpp
  tests/utils/util_tests.cpp
Labels: bugfix, utility

#93 Units simplification, plus more string utils tests
  src/ekat/util/ekat_rational_constant.hpp
  src/ekat/util/ekat_scaling_factor.hpp
  src/ekat/util/ekat_string_utils.cpp
  src/ekat/util/ekat_string_utils.hpp
  src/ekat/util/ekat_units.hpp
  tests/units/units.cpp
  tests/utils/CMakeLists.txt
  tests/utils/string_utils_tests.cpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, code cleanup, code quality, utility

#90 SCREAM: in debug mode, init workspace buffer with NaN
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
Labels: AT: AUTOMERGE, code quality, enhancement

#94 Added an import method to ParameterList, and added documentation
  src/ekat/ekat_parameter_list.cpp
  src/ekat/ekat_parameter_list.hpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, enhancement, utility

#95 Some modifications to Pack class
  src/ekat/ekat_pack.hpp
Labels: AT: AUTOMERGE, Packs, bugfix, code cleanup, code quality
