Repository E3SM-Project/EKAT, pull requests merged in 2021-09, with the labels that each got.

#131 EkatCreateUnitTest now runs unit tests serially if MPI_EXEC_NAME is omitted.
  cmake/EkatCreateUnitTest.cmake
  tests/CMakeLists.txt
  tests/logging/CMakeLists.txt
Labels: cmake, AT: AUTOMERGE, testing, mpi

#132 Print comm info before starting a catch test session.
  src/ekat/util/ekat_catch_main.cpp
Labels: enhancement, AT: AUTOMERGE, testing, mpi

#133 Only print_config on rank 0
  src/ekat/util/ekat_catch_main.cpp
  src/ekat/util/ekat_test_session.cpp
Labels: AT: AUTOMERGE, code cleanup

#138 Fix (and simplify) YAML parser
  src/ekat/ekat_parse_yaml_file.cpp
  tests/io/input.yaml
  tests/io/yaml_parser.cpp
Labels: bugfix, AT: AUTOMERGE

#139 Fix EkatCreateUnitTest
  cmake/EkatCreateUnitTest.cmake
Labels: cmake, bugfix, AT: AUTOMERGE

#140 Fix error in ekat_catch_main.cpp
  src/ekat/util/ekat_catch_main.cpp
Labels: bugfix, AT: AUTOMERGE, testing

#141 Reinstate running tests in a shell
  cmake/EkatCreateUnitTest.cmake
  tests/utils/CMakeLists.txt
  tests/utils/regress_fail.cpp
Labels: cmake, bugfix, AT: AUTOMERGE, testing

#137 Some mods to compiler flags and vectorization pragmas
  cmake/EkatSetCompilerFlags.cmake
  src/ekat/ekat_macros.hpp
  src/ekat/ekat_pack.hpp
  tests/pack/pack_tests.cpp
Labels: cmake, build, AT: AUTOMERGE, code cleanup

#142 Print only rank0
  src/ekat/ekat_session.cpp
Labels: AT: AUTOMERGE, code quality

#143 Do not use try-catch blocks when parsing YAML files
  src/ekat/ekat_parse_yaml_file.cpp
Labels: AT: AUTOMERGE, code cleanup, code quality

#144 Some safety fixes to the logic that generates the ekat_mpicxx wrapper script
  cmake/mpi/EkatSetNvccWrapper.cmake
Labels: cmake, bugfix, AT: AUTOMERGE

#145 Allow --map-by as MPI res specification flag, plus test-launcher script to wrap tests
  CMakeLists.txt
  bin/test-launcher
  cmake/EkatCreateUnitTest.cmake
  cmake/mpi/EkatMpiUtils.cmake
  src/ekat/util/ekat_catch_main.cpp
Labels: enhancement, AT: AUTOMERGE, testing, mpi

#146 Fix test-launcher for non-OpenMPI distros
  bin/test-launcher
Labels: bugfix, AT: AUTOMERGE, testing

#147 Cuda bug fix in WorkspaceManager initialization
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
Labels: bugfix, CUDA, AT: AUTOMERGE

#148 Add support for enabling cuda-memcheck
  CMakeLists.txt
  README.md
  cmake/EkatCreateUnitTest.cmake
Labels: cmake, CUDA, AT: AUTOMERGE, testing
