Repository E3SM-Project/EKAT, pull requests merged in 2022-11, with the labels that each got.

#264 Fix initialize_kokkos to follow Kokkos::Impl::parse_command_line_arguments.
  src/ekat/ekat_session.cpp
Labels: AT: AUTOMERGE

#266 Fix bug in TeamUtils get/release_workspace_idx for GPU.
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  tests/kokkos/workspace_tests.cpp
Labels: bugfix

#265 Fix cmake utility EkatDisableAllWarning
  cmake/EkatUtils.cmake
Labels: cmake, bugfix, AT: AUTOMERGE, AT: WIP

#267 Eliminating usage of Kokkos private headers.
  src/ekat/ekat_pack_utils.hpp
  src/ekat/ekat_workspace_impl.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
Labels: AT: AUTOMERGE, code quality

#268 Refine use of memory_fence in get/release_workspace_idx for GPU.
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  tests/kokkos/workspace_tests.cpp
Labels: AT: AUTOMERGE

#269 Rename scream->eamxx in jenkins script
  scripts/jenkins/jenkins_impl.sh
Labels: AT: AUTOMERGE
