Repository E3SM-Project/EKAT, pull requests merged in 2022-01, with the labels that each got.

#171 Add default constructor and setup() to WSM
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  tests/kokkos/workspace_tests.cpp
Labels: AT: AUTOMERGE, code usability

#174 Manage jenkins jobs with repo scripts similar to scream
  scripts/jenkins/jenkins.sh
  scripts/jenkins/jenkins_impl.sh
Labels: AT: AUTOMERGE

#173 Some meta-utils for type-list related metaprogramming
  src/ekat/util/ekat_meta_utils.hpp
  tests/utils/CMakeLists.txt
  tests/utils/meta_utils.cpp
Labels: AT: AUTOMERGE, utility

#175 Fix typo in jenkins script to set threading options
  scripts/jenkins/jenkins_impl.sh
Labels: bugfix, AT: AUTOMERGE, testing

#176 Add reset() for WSM
  src/ekat/ekat_workspace.hpp
  src/ekat/ekat_workspace_impl.hpp
  tests/kokkos/workspace_tests.cpp
Labels: AT: AUTOMERGE, code usability

#177 Add correct --kokkos args when none provided
  src/ekat/ekat_session.cpp
Labels: AT: AUTOMERGE, code cleanup, code quality
