Repository E3SM-Project/EKAT, pull requests merged in 2022-05, with the labels that each got.

#218 Add capability to dispatch TeamPolicy-based kernels on host in CUDA builds
  scripts/jenkins/jenkins_impl.sh
  src/ekat/ekat_workspace.hpp
  src/ekat/kokkos/ekat_kokkos_utils.hpp
  tests/kokkos/CMakeLists.txt
  tests/kokkos/kernel_on_host.cpp
Labels: enhancement, CUDA, AT: AUTOMERGE

#219 Add support for in-place mpi operations
  cmake/EkatMpiUtils.cmake
  src/ekat/mpi/ekat_comm.hpp
  tests/mpi/comm.cpp
Labels: enhancement, AT: AUTOMERGE, mpi, Quality Of Life

#221 Fixes a compilation issue with nvcc.
  src/ekat/io/ekat_yaml.cpp
Labels: CUDA, code usability
