Repository E3SM-Project/EKAT, pull requests merged in 2023-03, with the labels that each got.

#281 Replacing --kokkos-num-devices with --kokkos-map-device-id-by=mpi_rank.
  src/ekat/ekat_session.cpp
Labels: AT: AUTOMERGE, code cleanup

#282 Quality-of-life overload in ekat::any
  src/ekat/std_meta/ekat_std_any.hpp
  tests/utils/CMakeLists.txt
  tests/utils/std_meta.cpp
Labels: AT: AUTOMERGE, Quality Of Life

#283 Fix debug_tools tests in release mode
  tests/utils/debug_tools_tests.cpp
Labels: AT: AUTOMERGE

#284 Allow to pass a lambda to ekat::join
  src/ekat/util/ekat_string_utils.hpp
  tests/utils/string_utils_tests.cpp
Labels: enhancement, AT: AUTOMERGE, utility

#285 Avoid creating a modules folder for unit tests if no fortran files are to be compiled
  cmake/EkatCreateUnitTest.cmake
Labels: cmake, AT: AUTOMERGE, code cleanup

#286 Improve valgrind suppression file generation
  valgrind_support/CMakeLists.txt
  valgrind_support/mpi_catch_test.cpp
Labels: AT: AUTOMERGE

#289 [SYCL] Fix failed tests for PVC
  cmake/machine-files/jlse-xehp.cmake
  cmake/machine-files/kokkos/intel-pvc.cmake
  cmake/machine-files/sunspot-xehp.cmake
  src/ekat/util/ekat_math_utils.hpp
  src/ekat/util/ekat_tridiag.hpp
Labels: AT: AUTOMERGE, SYCL
