Repository E3SM-Project/EKAT, pull requests merged in 2024-04, with the labels that each got.

#332 Disable wsm_omp16 test when valgrind is on
  tests/kokkos/CMakeLists.txt
Labels: AT: AUTOMERGE

#333 Add `get_subview()` Implementations for Multi-Sliced Subfields
  src/ekat/kokkos/ekat_subview_utils.hpp
  tests/kokkos/kokkos_utils_tests.cpp
Labels: AT: AUTOMERGE

#334 Add cmake utility to create tests for asserts
  cmake/EkatCreateUnitTestWithAsserts.cmake
  cmake/gen_assert_test_src.py
  tests/utils/CMakeLists.txt
  tests/utils/assert_tests.cpp
Labels: cmake, AT: AUTOMERGE

#335 fix (in)equality for multi-sliced subview functions
  src/ekat/kokkos/ekat_subview_utils.hpp
Labels: bugfix, AT: AUTOMERGE
