Repository E3SM-Project/EKAT, pull requests merged in 2024-06, with the labels that each got.

#341 Fix warnings in subview utils
  src/ekat/kokkos/ekat_subview_utils.hpp
Labels: build, AT: AUTOMERGE, code cleanup

#342 Fix a few broken tests
  src/ekat/ekat_pack_kokkos.hpp
  tests/kokkos/kokkos_utils_tests.cpp
Labels: AT: AUTOMERGE

#343 GetMpiDistributionName: Fix for cray MPI
  cmake/EkatMpiUtils.cmake
Labels: cmake, bugfix, AT: AUTOMERGE

#344 Make copy constructor/assignment of ParameterList do a deep_copy
  src/ekat/ekat_parameter_list.cpp
  src/ekat/ekat_parameter_list.hpp
  src/ekat/std_meta/ekat_std_any.hpp
  tests/utils/util_tests.cpp
Labels: AT: AUTOMERGE, code quality, code usability

#345 Fix unused var warning in release build
  src/ekat/util/ekat_scaling_factor.hpp
  src/ekat/util/ekat_units.hpp
  tests/algorithm/tridiag_tests_correctness.cpp
  tests/kokkos/kokkos_utils_tests.cpp
  tests/kokkos/workspace_tests.cpp
Labels: AT: AUTOMERGE, code cleanup
